### PR TITLE
WIP: Adding Corsair's Ironclaw Wireless mouse

### PR DESCRIPTION
**Pull request by Electro707**
This is my attempt at adding the Ironclaw Wireless mouse. 

[Link to mouse's page](https://www.corsair.com/us/en/Categories/Products/Gaming-Mice/Wireless-Gaming-Mice/IRONCLAW-RGB-WIRELESS-Gaming-Mouse/p/CH-9317011-NA)

I have so far added a graphic for the mouse based on the wired Ironclaw, and started to add the mouse into the program.

Note: This PR in WIP!

### CODE REVIEW

**Comment by Electro707** [comment]
image
There seems to be a "broken pipe" on the USB port/dev for this device.

**Comment by Ravenslofty** [comment]
You'll need to implement the Bragi protocol to get the Ironclaw Wireless to work; it's quite likely that the NXP init sequence is possibly causing bugs in the firmware making the mouse hang (which is what the "Broken pipe" error is).

**Comment by Ravenslofty** [comment]
Marked this as a draft so it can't accidentally get merged.

**Comment by Electro707** [comment]
I have captured my Ironclaw using Wireshark while not moving (was using another mouse to control the computer). usbpcap seems to reset the device when the capture started, which is why there is the device descriptors initially. Then, I loaded Icue (without doing anything to the mouse). Hopefully this will be useful.

Note: To get only the Ironclaw, run this filter: `usb.device_address==2`

Link to capture file: [HERE!](https://drive.google.com/file/d/1jVZqTdwTZmVJd732d5ovHdZJ2FGq2Pcz/view?usp=sharing)

**Comment by Electro707** [comment]
Here is a capture of Icue already loaded but in the "Hardware Lightning" screen. I am assuming that the data packets are of the software requesting the current RGB color to preview in it's software

[Link to lightning preview data packet](https://drive.google.com/file/d/1jVZqTdwTZmVJd732d5ovHdZJ2FGq2Pcz/view?usp=sharing)

**Comment by Electro707** [comment]
I have created a repository containing all my captures, python program to interpret the data, and a documentation of my findings so far.

[Repository Link](https://github.com/Electro707/Ironclaw_Wireless_Reverse_Engineering)

I have also so far successfully found out which data packets are required to change the mouse's RGB colors (on the logo, front of the mouse, and scroll-wheel in the case of this mouse). That is documented on my reverse-engineering repository.

**Comment by Electro707** [comment]
As an update to this PR/my fork I have, since a bit ago and just recently refined it, added custom layouts for the LED and bindings menu. Yes the LED on the right is intentionally not on top of the mouse, I think it would signal the side LEDs better.
image
image

As a side thing, I've also made it so that the mouse's image expands if the program is expanded for a larger mouse GUI (still working on the keyboard due to the way the background is generated).

**Comment by notabot27** [comment]
Are there any upadates to this? I just got the mouse.

**Comment by NicTanghe** [comment]
Hello evryone,
I thought i had read somewhere that this was already merged into the main bransh.
I just switched mice and it`s not being detected.

I whould love this to be fixed.
TO bad it`s stale

**Pull request closed without merging**
