### PR TITLE
Rename UDEV rules file

### PR DESCRIPTION
**Pull request by dguglielmi**
Use same file naming as other files (systemd unit, openrc init, etc..)

### CODE REVIEW

**Comment by tatokis** [comment]
Can you please also make cmake try to uninstall the old file during installation when SAFE_INSTALL is on?
I can see this leading to various issues with rules conflicting because the old one is still installed on systems.

**Comment by urmamasllama** [comment]
Could we also get symlinks to the event devices. I've been having a time setting up evdev passthrough. If it's wanted I can clean up the rules file I'm currently using and share.

**Comment by tatokis** [comment]
@urmamasllama it's currently WIP https://github.com/ckb-next/ckb-next/issues/212

**Comment by tatokis** [comment]
@urmamasllama Sorry, I should've made it more clear. Please do share your rules in the issue I linked above, as this PR is not related to evdev.
Thank you.

**Comment by dguglielmi** [comment]
@tatokis sure, i'll take a look at this quickly.

**Comment by tatokis** [comment]
@dguglielmi Are you still interested in working in this? If not I'll close it.

**Pull request closed without merging**
