### PR TITLE
WIP Headset Support

### LINKED ISSUE #81: Void headset support
I'm putting this in a separate issue so that we don't pollute #52.

From @aldistuck:
[CorsairUSBVoid.pcapng.gz](https://github.com/ckb-next/ckb-next/files/1709461/CorsairUSBVoid.pcapng.gz)
I attempted to use Wireshark to capture usb communication from my Corsair usb Void headset (corded). From the start the UI could see usb connections. One of them contained the headset so I just started a capture on that so I'm assuming everything in this is only between the headset and what the capture was calling the host. Nothing began happening until I opened the CUE 2 software (captured this on Windows 10). Once CUE 2 was open I started seeing data in Wireshark. I went to the settings for the headset and cycled through all the settings for lighting effects, EQ, and infomic. I hope this is helpful information.

[CorsairUSBVoid-0.pcapng.gz](https://github.com/ckb-next/ckb-next/files/1709571/CorsairUSBVoid-0.pcapng.gz)
[CorsairUSBVoid-1.pcapng.gz](https://github.com/ckb-next/ckb-next/files/1709572/CorsairUSBVoid-1.pcapng.gz)
Here are a couple more traces I recorded. I opened up a youtube video to get audio going through the headset. The -1 capture seems to have an additional source I did not have prior.

### PR DESCRIPTION
**Pull request by SethBarberee**
- [X] Headset recognized by daemon
- [X] Headset recognized by GUI
- [ ] RGB Control <- Getting errors when sending the message so working on that (uncomment the usbsend and it'll stall)

Fixes #81 

If you wanna test if the daemon picks up your headset, please do and let me know if I need to add more usbid's for respective headset

@tatokis since you did the RGB part. My IRL schedule is pretty free all Thursday (CST) and most of Tuesday afternoon if I need to get on IRC to help with testing.

### CODE REVIEW

**Comment by kevhawk2914** [comment]
Tried it out with my headset, changed the P_VOID_WIRELESS_1 in usb.h to 1b1c with no luck for even recognizing it sadly.

Bus 005 Device 004: ID 1b1c:0a2c Corsair Corsair VOID RGB Wireless Gaming Headset
Bus 001 Device 003: ID 1b1c:0a2b Corsair Corsair VOID Wireless Gaming Dongle

**Comment by tatokis** [comment]
Please don't destroy commit history like that, especially when it's from multiple authors.

That aside, last I checked my RGB code worked for a specific void. Unfortunately most voids have different protocols/registers from what I remember.

Especially the wireless void has different commands/registers.

If my RGB code doesn't work after the rebase, it's possible because I remember changing the usbsend control function and adding more parameters for the legion branch.

Either way, please force push with a proper rebase of the void branch if you want and we can go from there.

I've not really wanted to work on this for quite a while now, which is why it's been idle, but if you poke me on irc we can have a look.

**Comment by thespyboss** [comment]
@SethBarberee I am getting a Void Wireless headset this weekend and will be able to help out test if needed.

**Comment by FlashOnFire** [comment]
I can test with my wired void tomorrow.

**Comment by SabbathHex** [comment]
I will test the daemon with my device `0a14`, but I really do not want to build the qt packages. Are there any console-based tests for the animation I could run? 

Also, if needed, I have VMs running Gentoo and Windows, so if there is any additional information I could supply to help push this forward - let me know.

**Comment by SethBarberee** [comment]
> Please don't destroy commit history like that, especially when it's from multiple authors.

@tatokis I did not mean to do that. I was trying to get it to work again and so I started from a fresh branch. I will fix the git history. Apologies.

**Comment by SethBarberee** [comment]
> Edit: I was mistaken, shouldn't have been using 1b1c it detects it now with 0a2c on the daemon.
@kevhawk2914 gotcha, I can add that ID into the detection.

**Comment by FlashOnFire** [comment]
It doesn't detect my headset. I had to add it manually. Now it detects it but the colors still don't work.

My headset : (found in lsusb)
`Bus 003 Device 010: ID 1b1c:0a17 Corsair`

**Comment by thespyboss** [comment]
@SethBarberee where do i add the id for the headset? im getting mine tomorrow and wanted to know in advance.

**Comment by SethBarberee** [comment]
@FlashOnFire correct, GUI control doesn't work yet as stated at the top. 

Try to `echo active > /dev/input/ckb<number of headset>/cmd` to see if it at least gets control of it.

> @SethBarberee where do i add the id for the headset? im getting mine tomorrow and wanted to know in advance.

There are three spots:
Here:
https://github.com/ckb-next/ckb-next/pull/528/files#diff-cfd45abdce8c1ff35bbfe26b6dbaeb98R127
And Here:
https://github.com/ckb-next/ckb-next/pull/528/files#diff-e238f9fce6b20ae82bc2ea2c1457ead3R84
And Here:
https://github.com/ckb-next/ckb-next/pull/528/files#diff-e238f9fce6b20ae82bc2ea2c1457ead3R187

If it doesn't detect it, just run `lsusb -v ` to find the id and I can add it in my next patches of IDs since there's a few VOIDs.

**Comment by FlashOnFire** [comment]
@SethBarberee how can i find the number of headset ?

**Comment by thespyboss** [comment]
@SethBarberee I installed your version of ckb and it didn't detect my void. This is the title that i got for my headset: Bus 001 Device 005: ID 1b1c:1b27 Corsair Corsair VOID Wireless Gaming Dongle

**Comment by thespyboss** [comment]
@SethBarberee also my idProduct is the same thing as the line in this link: https://github.com/ckb-next/ckb-next/pull/528/files#diff-cfd45abdce8c1ff35bbfe26b6dbaeb98R127
Which is weird bc ckb isnt showing my headset.

**Comment by thespyboss** [comment]
Screenshot from 2020-01-19 17-59-55 this is what the terminal is showing me. there is more but this is the necessary part from what i know.

**Comment by SethBarberee** [comment]
@thespyboss logs from when you ran it?

@FlashOnFire when the daemon starts, it lists which ckb number the void is on

**Comment by thespyboss** [comment]
@SethBarberee i actually think its detecting it but its not on the gui but from reading the commentd above the gui doesn't work. how do i send commands to the headset to change its color then? this is what terminal gave me just to make sure im not wrong. 
Screenshot from 2020-01-19 18-31-47

**Comment by theLMGN** [comment]
Not working with VOID Pro Wireless RGB

```
Corsair VOID PRO Wireless Gaming Headset:

  Product ID:	0x0a14
  Vendor ID:	0x1b1c  (CORSAIR MEMORY INC.)
  Version:	0.00
  Speed:	Up to 12Mb/sec
  Manufacturer:	Corsair
  Location ID:	0x14a00000 / 8
  Current Available (mA):	500
  Current Required (mA):	100
  Extra Operating Current (mA):	0

```

**Comment by SabbathHex** [comment]
@theLMGN I have the same device. The patch replacing `P_VOID_WIRELESS_1` value to `0x0a14` is necessary to make it work.

```
--- a/src/daemon/usb.h
+++ b/src/daemon/usb.h
@@ -115,7 +115,7 @@
 
 #define P_VOID_USB_1         0x1b29
 #define P_VOID_USB_2         0x1b2a
-#define P_VOID_WIRELESS_1    0x1b27
+#define P_VOID_WIRELESS_1    0x0a14
 #define IS_VOID(kb)          ((kb)->vendor == V_CORSAIR && ((kb)->product == P_VOID_USB_1 || (kb)->product == P_VOID_USB_2 || (kb)->product == P_VOID_WIRELESS_1))
```

**Comment by thespyboss** [comment]
Is the headset supposed to pop up in the GUI? Im not getting anything on the gui but the headset is working fine. This is my headset from my posts from above. 
image

**Comment by theLMGN** [comment]
No GPG2 or GPG detected. Signature verification disabled.
Using QSytemTrayIcon
Path to settings: "/Users/thelmgn/.config/ckb-next/ckb-next.ini"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/gradient"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/heat"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/invaders"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/life"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/pinwheel"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/pipe"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/rain"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/random"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/ripple"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/snake"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/wave"
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
QPngHandler: Failed to parse ICC profile
[...lines repeated...]
Starting "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/ripple"
Starting "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/gradient"
Downloaded new firmware list. 38 entries found.

**Comment by theLMGN** [comment]
@SabbathHex Still not working. Output from console:
```

No GPG2 or GPG detected. Signature verification disabled.
Using QSytemTrayIcon
Path to settings: "/Users/thelmgn/.config/ckb-next/ckb-next.ini"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/gradient"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/heat"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/invaders"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/life"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/pinwheel"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/pipe"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/rain"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/random"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/ripple"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/snake"
Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/wave"
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: fromIccProfile: failed general sanity check
QPngHandler: Failed to parse ICC profile
[...lines repeated...]
Starting "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/ripple"
Starting "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/gradient"
Downloaded new firmware list. 38 entries found.```

**Comment by SabbathHex** [comment]
@theLMGN judging by path names - you might be using macOS. My solution probably is Linux-specific

**Comment by zKauaCodes** [comment]
@SabbathHex 
I would like to know how to make corsair void pro wireless appear in the gui

**Comment by SabbathHex** [comment]
@zKauacodes,
Afraid I can't help you since I do not build this with gui, qt packages are masked on my machines. They take too long to compile, and my primary use case is to make the annoying leds to go away and not waste battery.

**Comment by Rechdan** [comment]
After this issue, will the Void work with 7.1 surround sound? Thanks!

**Comment by thespyboss** [comment]
@Rechdan I think eventually but we would need to program it in. For now i think the project is getting the leds to work and be able to change them.

**Comment by st0nkz** [comment]
I have a Void PRO Wireless, would that work?

**Comment by SabbathHex** [comment]
@st0nkz you might need the same patch from [my previous comment](https://github.com/ckb-next/ckb-next/pull/528#issuecomment-581617372).

**Comment by ferrettim** [comment]
Not sure what the status of this is but I am using [HeadsetControl](https://github.com/Sapd/HeadsetControl) simply to shut off the RGB on my wireless Void PRO RGB so maybe taking a look at the source for that project could advance the status of this issue?

**Comment by thespyboss** [comment]
@ferrettim Thats not a bad idea. I just looked through it and im suggesting @SethBarberee if this could be implemented eventually. Im not sure how but this is a feature we would eventually use or need.

**Comment by SethBarberee** [comment]
Finals are currently underway here and graduation from college. That being said, I managed to rebase most of the branch with the old commits. I don't want to add new functionality until basic functionality works. I believe the initialization is the current issue with the void since it will hang on that part with a return of -1 and broken pipe. I probably will need to do a new capture on wireshark but will not have the chance until next month. 
If someone else gets a capture of the following on a USB Void, it'll be helpful:
* plugging and unplugging a USB Void
* changing the RGB

I'm hoping to get more captures once finals end. Once I fix local build errors, I will re-push with fixed git history, @tatokis.

**Comment by thespyboss** [comment]
@SethBarberee I got tons of time on hand to do that. Could you give me some tips on how to do that and if I get the data, where would you want me to send it. Since my school is closed and online schooling is going on, I have too much free time it seems like!

**Comment by SethBarberee** [comment]
Packet sniffed and verified that packets are expected for initialization. Which led me down the path of usbsend verification

Compiled the base void version and verified that daemon rgb control works. I'm assuming that the usbsend changes are the main cause because the void sends messages less than 64 bytes during the initialization.

**Comment by lincolnBerlick** [comment]
i have a corsair void wireless rgb, what can i do with her if install this branch?

**Comment by SethBarberee** [comment]
Found some more time this weekend so will try to update/rebase this branch in the upcoming week.

**Comment by SethBarberee** [comment]
Closing in favor of #641 (mainly for updated git history). Sorry about that, @tatokis.

**Pull request closed without merging**
