### PR TITLE
Add K63 NRGB Wireless ID

### PR DESCRIPTION
**Pull request by ZirconiumX**
The easy part of fixing #74.

### CODE REVIEW

**Comment by ZirconiumX** [comment]
@felbus can you see if the daemon picks up the keyboard with this? Preferably join us in IRC as well.

**Comment by felbus** [comment]
trying..

**Comment by felbus** [comment]
Thanks for the commit. I removed previous code. Checked out this branch, ran quickinstall, still got no devices connected.

**Comment by felbus** [comment]
irc details?

**Comment by ZirconiumX** [comment]
Yes, you're joining our channel, and then leaving again.

**Comment by xipher1** [comment]
I have a k63 + high sierra, happy to test anything you guys need.

**Pull request closed without merging**
