### PR TITLE
Replace K68 with K68_NRGB

### PR DESCRIPTION
**Pull request by mauriciofauth**

### CODE REVIEW

**Comment by ZirconiumX** [comment]
Does this build cleanly? That's the only reason I'm holding off merging this.

**Comment by mauriciofauth** [comment]
Yes. It's the version I'm using now.

**Comment by tatokis** [comment]
If no one else does, I'll test it tomorrow.

**Comment by ZirconiumX** [comment]
On your head be it.

We really need to get Travis set up.

**Comment by tatokis** [comment]
No need to be rude about it.

**Pull request merged**
