### PR TITLE
add support to "Corsair Dark Core RGB Pro" as experimental

### PR DESCRIPTION
**Pull request by gilvbp**
add support to "Corsair Dark Core RGB Pro" as experimental thanks to @Clofriwen

This adds support for the Corsair Dark Core RGB Pro mouse. The product page is here: https://www.corsair.com/br/pt/Categorias/Produtos/Mouses-gamer/Wireless-Gaming-Mice/DARK-CORE-RGB-PRO-Wireless-Gaming-Mouse/p/CH-9315411-NA

Its interface is fairly similar to the SE,

I've tested this with my mice, almost everything is fully functional.

### CODE REVIEW

**Comment by Clofriwen** [comment]
Here the cleaned version
[ckb-next-0.5.0-Dark_Core_RGB_Pro.2.tar.gz](https://github.com/ckb-next/ckb-next/files/8807971/ckb-next-0.5.0-Dark_Core_RGB_Pro.2.tar.gz)
[Dark_Core_RGB_Pro-Patch.2.tar.gz](https://github.com/ckb-next/ckb-next/files/8807973/Dark_Core_RGB_Pro-Patch.2.tar.gz)

**Comment by immerautumn** [comment]
I also hope/want this commit merged, this adds support for a number of Dark Core RGB models, including the SE and SE Wireless. Very nice! Thanks! 

The current version I have does not detect my Dark Core RGB SE WL via the dongle.

**Comment by Clofriwen** [comment]
Hello,

You have same device like mine (and it's work in wired & wireless mode).
That still in experimental, also, you need to start daemon as super user with : "`ckb-next-daemon --enable-experimental`".

You can remove experimental by replacing in "`src/daemon/usb.h`" this line :
`#define IS_EXPERIMENTAL(vendor, product) ((vendor) == V_CORSAIR && ((product) == P_K63_NRGB_WL || (product) == P_K63_NRGB_WL2 || (product) == P_K63_NRGB_WL3 || (product) == P_K63_NRGB_WL4 || (product) == P_DARK_CORE || (product) == P_DARK_CORE_WL || (product) == P_DARK_CORE_SE || (product) == P_DARK_CORE_SE_WL || (product) == P_IRONCLAW_W_U || (product) == P_IRONCLAW_W_D || (product) == P_DARK_CORE_RGB_PRO_SE || (product) == P_DARK_CORE_RGB_PRO_SE_WL || (product) == P_HARPOON_WL_U || (product) == P_HARPOON_WL_D || (product) == P_K57_U || (product) == P_K57_D))`
by this one :
`#define IS_EXPERIMENTAL(vendor, product) ((vendor) == V_CORSAIR && ((product) == P_K63_NRGB_WL || (product) == P_K63_NRGB_WL2 || (product) == P_K63_NRGB_WL3 || (product) == P_K63_NRGB_WL4 || (product) == P_DARK_CORE || (product) == P_DARK_CORE_WL || (product) == P_DARK_CORE_SE || (product) == P_DARK_CORE_SE_WL || (product) == P_IRONCLAW_W_U || (product) == P_IRONCLAW_W_D || (product) == P_HARPOON_WL_U || (product) == P_HARPOON_WL_D || (product) == P_K57_U || (product) == P_K57_D))`

**Comment by dragonhelios** [comment]
First off thanks for the great work by everyone.

I thought I would just add to my test results for the Corsair Dark Core RGB Pro SE. 

In both wired and wireless mode I get the following errors: 

[E] os_usb_interrupt_out (via bragi_common.c:9): Connection timed out, res = 0xffffffff
&&
[F] start_bragi_common (device_bragi.c:103): ckb1: Couldn't get bragi device mode. Aborting

In wired mode: The Mouse is immediately picked up in ckb-next. After a while the dongle is picked up as well, which I assume is delayed due to the bragi errors. 

In wireless (2.4Ghz mode) I only get the dongle and not the mouse itself in ckb-next.

Also to note is when I ran it initially I was confronted with the mouse cursor not moving and an error: "[E] process_input_urb (keymap.c:731): Unknown bragi data received in input thread 00 from endpoint 82" when ever I moved the mouse. After stopping and restarting the service this was no longer the case and the cursor moved perfectly.

I've attached output for both wired and wireless modes
[output_wired.txt](https://github.com/ckb-next/ckb-next/files/8840666/output_wired.txt)
[output_wirless.txt](https://github.com/ckb-next/ckb-next/files/8840667/output_wirless.txt)
.

**Comment by dragonhelios** [comment]
changed usb port and it seems to have resolved the issue

**Comment by gilvbp** [comment]
> Here the cleaned version (see [#716 (comment)](https://github.com/ckb-next/ckb-next/issues/716#issuecomment-1142365221)) [ckb-next-0.5.0-Dark_Core_RGB_Pro.2.tar.gz](https://github.com/ckb-next/ckb-next/files/8807971/ckb-next-0.5.0-Dark_Core_RGB_Pro.2.tar.gz) [Dark_Core_RGB_Pro-Patch.2.tar.gz](https://github.com/ckb-next/ckb-next/files/8807973/Dark_Core_RGB_Pro-Patch.2.tar.gz) (discharging stats still don't work)

Thanks, I will update the code.

**Comment by Clofriwen** [comment]
Hello,

I permit @gilvbp to commit for me, but I keep the right to commit by myself if I need.

That will be Ok like this ?

**Comment by daugustin** [comment]
Does this currently build for you?

When trying to build your branch I get:

```
/tmp/ckb-next/src/gui/keywidget.cpp: In member function ‘virtual void KeyWidget::paintEvent(QPaintEvent*)’:
/tmp/ckb-next/src/gui/keywidget.cpp:156:17: error: ‘darkCoreRgbProOverlay’ was not declared in this scope; did you mean ‘darkCoreOverlay’?
  156 |             if(!darkCoreRgbProOverlay)
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 darkCoreOverlay
/tmp/ckb-next/src/gui/keywidget.cpp:158:23: error: ‘darkCoreRgbProOverlay’ was not declared in this scope; did you mean ‘darkCoreOverlay’?
  158 |             overlay = darkCoreRgbProOverlay;
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       darkCoreOverlay
```

**Comment by tatokis** [comment]
@Clofriwen I am not a lawyer, so I do not know.

**Comment by Clofriwen** [comment]
Hello,

> Does this currently build for you?
> 
> When trying to build your branch I get:
> 
> ```
> /tmp/ckb-next/src/gui/keywidget.cpp: In member function ‘virtual void KeyWidget::paintEvent(QPaintEvent*)’:
> /tmp/ckb-next/src/gui/keywidget.cpp:156:17: error: ‘darkCoreRgbProOverlay’ was not declared in this scope; did you mean ‘darkCoreOverlay’?
>   156 |             if(!darkCoreRgbProOverlay)
>       |                 ^~~~~~~~~~~~~~~~~~~~~
>       |                 darkCoreOverlay
> /tmp/ckb-next/src/gui/keywidget.cpp:158:23: error: ‘darkCoreRgbProOverlay’ was not declared in this scope; did you mean ‘darkCoreOverlay’?
>   158 |             overlay = darkCoreRgbProOverlay;
>       |                       ^~~~~~~~~~~~~~~~~~~~~
>       |                       darkCoreOverlay
> ```

I think you forgot to modify "static QImage*" at line 12 as (you need : ***darkCoreRgbProOverlay = nullptr**) :
`static QImage* m65Overlay= nullptr, *sabOverlay= nullptr, *scimOverlay= nullptr, *harpOverlay= nullptr, *glaiveOverlay= nullptr, *polarisOverlay= nullptr, *katarOverlay= nullptr, *m95Overlay= nullptr, *ironclawOverlay= nullptr, *nightswordOverlay= nullptr, *darkCoreOverlay = nullptr, *darkCoreRgbProOverlay = nullptr, *ironclawWirelessOverlay= nullptr, *glaiveproOverlay= nullptr,* m55Overlay= nullptr;`

(or add `static QImage*darkCoreRgbProOverlay = nullptr;` after include section)

**Comment by Clofriwen** [comment]
New pull opened at this place : https://github.com/ckb-next/ckb-next/pull/855
- that made from an current master version
- support an corrected battery status (improved compatibility with nxp protocole (Dark Core))

**Pull request closed without merging**
