### PR TITLE
Fix slow power off and reboot for strafe keyboard.

### PR DESCRIPTION
**Pull request by TOKYEO**
I fixed a bug where power off and reboot was slow because the strafe keyboard will hang.

### CODE REVIEW

**Comment by tatokis** [comment]
I don't remember this being an issue with the strafe. Have you tried the HID quirks first? If the quirks fix it, then the issue should be fixed in the kernel. I'd like to have as few devices as possible in the unclean exit list.
https://github.com/ckb-next/ckb-next/wiki/Troubleshooting#usbhid-quirks

**Comment by TOKYEO** [comment]
Oh ok, thank you! I will try it out and let you know.

**Comment by TOKYEO** [comment]
Really sorry to bother you, but what shall I do once I have found my specific USBCore/USBHID quirks?

**Comment by TOKYEO** [comment]
Thank you for the input. Adding the HID to the kernel command line parameter worked. My reboot is now at a normal speed.

Thank you for your time,
TOKYEO

**Pull request closed without merging**
